### ISSUE TITLE
Сверстать чекбокс

### ISSUE THREAD

**Issue by isqua** [IgorYarutkin/mishka#4]
Вот такой:

<img width="284" alt="checkbox" src="https://cloud.githubusercontent.com/assets/529247/19019963/295a2c78-88a3-11e6-9295-10f7793bfff9.png">

Во всех разрешениях и состояниях. Галочку можно делать svg.

**Comment by IgorYarutkin** [comment]
Галочку фоном?

**Comment by isqua** [comment]
Галочку — чтобы работало. А как — не важно.

**Comment by isqua** [comment]
Смотри, ишья не закрылась из-за того, что в названии пулл-реквеста между `fix` и `#4` нет пробела. Закрой ишью руками и будь внимательнее в следующий раз.
